### ISSUE TITLE
Error on install

### ISSUE THREAD

**Issue by dawood2014** [dereneaton/ipyrad#272]
I just went through the install directions for a mac and tried the following command ipyrad -h and get this error:

Traceback (most recent call last):
  File "/Users/dawood/miniconda2/bin/ipyrad", line 6, in <module>
    from pkg_resources import load_entry_point
ImportError: No module named pkg_resources

Any susggestions?

**Comment by isaacovercast** [comment]
There's probably another version of python installed that's conflicting
with miniconda. Did you install miniconda from scratch? If not, then I'd
recommend removing the miniconda directory and reinstalling from scratch.
You could also inspect the results of `echo $PATH` and `which python` get
more information.

You could also try running ipyrad in a conda env (docs:
https://conda.io/docs/user-guide/tasks/manage-environments.html).

Also you could try blanking the PYTHONPATH:
http://ipyrad.readthedocs.io/faq.html?highlight=pythonpath#collisions-with-other-local-python-conda-installs

**Comment by dawood2014** [comment]
I had an older version of anaconda installed. But I tried deleting that and then reinstall miniconda and the same error occurs.

**Comment by isaacovercast** [comment]
Looks like there's an issue with the conda install package. If you run:

`conda install setuptools`

it should fix this problem. We'll update the conda requirements and push a new package soon.

**Comment by isaacovercast** [comment]
Fixed in 0.7.15. You can fix this by hand in one of two ways:

```
conda install setuptools
```

or

```
conda remove ipyrad
conda install -c ipyrad ipyrad
```

**Comment by dawood2014** [comment]
Tried both solutions that you recommended and this is what was returned
after calling ipyrad:

WERCs-MacBook-Pro:~ dawood$ ipyrad -h

Traceback (most recent call last):

  File "/Users/dawood/miniconda2/bin/ipyrad", line 6, in <module>

    from pkg_resources import load_entry_point

  File
"/Users/dawood/miniconda2/lib/python2.7/site-packages/pkg_resources/__init__.py",
line 3138, in <module>

    @_call_aside

  File
"/Users/dawood/miniconda2/lib/python2.7/site-packages/pkg_resources/__init__.py",
line 3122, in _call_aside

    f(*args, **kwargs)

  File
"/Users/dawood/miniconda2/lib/python2.7/site-packages/pkg_resources/__init__.py",
line 3151, in _initialize_master_working_set

    working_set = WorkingSet._build_master()

  File
"/Users/dawood/miniconda2/lib/python2.7/site-packages/pkg_resources/__init__.py",
line 664, in _build_master

    ws.require(__requires__)

  File
"/Users/dawood/miniconda2/lib/python2.7/site-packages/pkg_resources/__init__.py",
line 981, in require

    needed = self.resolve(parse_requirements(requirements))

  File
"/Users/dawood/miniconda2/lib/python2.7/site-packages/pkg_resources/__init__.py",
line 867, in resolve

    raise DistributionNotFound(req, requirers)

pkg_resources.DistributionNotFound: The 'jupyter' distribution was not
found and is required by ipyrad

Dustin A. Wood
Geneticist

U.S. Geological Survey
Western Ecological Research Center
San Diego Field Station
4165 Spruance Road, Suite 200
San Diego, CA 92101
Phone: (619) 225-6432

Current Projects and Publication list <http://orcid.org/0000-0002-7668-9911>

**Comment by dawood2014** [comment]
Hi Isaac for all your help this weekend.
The force install of jupyter gave the same errors. It still can't find it,
so it seems to be using another python like you said. But when I run the
commands you suggested earlier, it doesn't look like it's using a different
one (at least to to this hack).

When I run which python,then I get:

/Users/dawood/miniconda2/bin/python

When I run  which -a python, then I get:

/Users/dawood/miniconda2/bin/python

/Users/dawood/miniconda2/bin/python

/Users/dawood/miniconda2/bin/python

/usr/bin/python

When I run $PATH, then I get

bash:/Users/dawood/miniconda2/bin:/Users/dawood/miniconda2/bin:/Users/dawood/miniconda2/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/sbin:
No such file or directory
Thanks again!

**Comment by isaacovercast** [comment]
Hm, so the `jupyter` install worked, but then ipyrad still errored out in the same way? is that correct? lets try something else. Can you post the results of this:

`env`

Also, can I see the results of this:

`which -a python2.7`

**Comment by dawood2014** [comment]
Yes, that is correct. Below are the results from the two commands you
requested.

WERCs-MacBook-Pro:~ dawood$ env
TERM_PROGRAM=Apple_Terminal
SHELL=/bin/bash
TERM=xterm-256color
TMPDIR=/var/folders/sn/vjwm7fn51p7fh16dq9rb5svc001j02/T/
Apple_PubSub_Socket_Render=/private/tmp/com.apple.launchd.oCaX7iEToQ/Render
TERM_PROGRAM_VERSION=388.1.1
TERM_SESSION_ID=64D95807-04D5-475B-8EDE-44DAB56D9D34
USER=dawood
SSH_AUTH_SOCK=/private/tmp/com.apple.launchd.CDb4BemQDN/Listeners
__CF_USER_TEXT_ENCODING=0xC402:0x0:0x0
PATH=/Users/dawood/miniconda2/bin:/Users/dawood/miniconda2/bin:/Users/dawood/miniconda2/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/sbin
PWD=/Users/dawood
LANG=en_US.UTF-8
XPC_FLAGS=0x0
XPC_SERVICE_NAME=0
SHLVL=1
HOME=/Users/dawood
LOGNAME=dawood
_=/usr/bin/env

WERCs-MacBook-Pro:~ dawood$ which -a python2.7
/Users/dawood/miniconda2/bin/python2.7
/Users/dawood/miniconda2/bin/python2.7
/Users/dawood/miniconda2/bin/python2.7
/usr/bin/python2.7

**Comment by isaacovercast** [comment]
Nothing too unusual there. How about `conda list`?

**Comment by dawood2014** [comment]
WERCs-MacBook-Pro:~ dawood$ conda list
# packages in environment at /Users/dawood/miniconda2:
#
alabaster                 0.7.10           py27h9dd7d6e_0
appnope                   0.1.0            py27hb466136_0
asn1crypto                0.22.0                   py27_0
babel                     2.5.0            py27h7311c9e_0
backports                 1.0              py27hb4f9756_1
backports.shutil_get_terminal_size 1.0.0            py27hc9115de_2
backports_abc             0.5              py27h6972548_0
bleach                    2.0.0            py27ha7d1710_0
bokeh                     0.12.9           py27h12a3c79_0
certifi                   2017.7.27.1      py27h482ffc0_0
cffi                      1.10.0                   py27_0
click                     6.7              py27h2b86a94_0
cloudpickle               0.4.0            py27h665dddb_0
conda                     4.3.27           py27h94ab009_0
conda-env                 2.6.0                h36134e3_0
configparser              3.5.0            py27hc7edf1b_0
cryptography              1.8.1                    py27_0
curl                      7.54.1                        0
cutadapt                  1.12             py27h3ab3c0e_0    ipyrad
cython                    0.26.1           py27h6a053f9_0
dask                      0.15.3           py27h8a1b457_0
dask-core                 0.15.3           py27h6a32bf4_0
decorator                 4.1.2            py27h9f877ea_0
distributed               1.19.1           py27h67dd2ec_0
docutils                  0.14             py27h0befae3_0
entrypoints               0.2.3            py27hd680fb1_2
enum34                    1.1.6                    py27_0
funcsigs                  1.0.2            py27hb9f6266_0
functools32               3.2.3.2          py27h8ceab06_1
futures                   3.1.1            py27hb02a37a_0
h5py                      2.7.0               np113py27_0
hdf5                      1.8.17                        2
heapdict                  1.0.0            py27hb5e74ad_0
html5lib                  0.999999999      py27hec7e2bc_0
icu                       54.1                          0
idna                      2.5                      py27_0
imagesize                 0.7.1            py27h4f7bcc8_0
intel-openmp              2018.0.0             hdd0ccc9_7
ipaddress                 1.0.18                   py27_0
ipykernel                 4.6.1            py27h1e70a78_0
ipyparallel               6.0.2                    py27_0
ipyrad                    0.7.15               h4f5177b_4    ipyrad
ipython                   5.4.1            py27h2b3d779_1
ipython_genutils          0.2.0            py27h8b9a179_0
ipywidgets                7.0.0            py27h3e52029_0
jinja2                    2.9.6            py27h92590e2_1
jsonschema                2.6.0            py27hd9b497e_0
jupyter                   1.0.0            py27hec63c99_0
jupyter_client            5.1.0            py27hfaf569a_0
jupyter_console           5.2.0            py27h9702a86_1
jupyter_core              4.3.0            py27hd5161ba_0
krb5                      1.13.2                        0
libcxx                    4.0.1                h579ed51_0
libcxxabi                 4.0.1                hebd6815_0
libgcc                    4.8.5               hdbeacc1_10
libgfortran               3.0.1                h93005f0_2
libsodium                 1.0.13               hba5e272_2
libssh2                   1.8.0                h1218725_2
llvmlite                  0.20.0                   py27_0
locket                    0.2.0            py27ha10513d_1
markupsafe                1.0              py27hd3c86fa_1
mistune                   0.7.4            py27h1658d75_0
mkl                       2018.0.0             hc285769_4
mpi4py                    2.0.0                    py27_0
msgpack-python            0.4.8            py27h635ded4_0
nbconvert                 5.3.1            py27h6455e4c_0
nbformat                  4.4.0            py27hddc86d0_0
networkx                  1.11             py27h0a72f81_0
notebook                  5.0.0            py27h5f5981d_2
numba                     0.35.0              np113py27_6
numpy                     1.13.1           py27hd567e90_2
openmpi                   1.6.3                         1
openssl                   1.0.2l                        0
packaging                 16.8                     py27_0
pandas                    0.20.3           py27h2a3d8ca_2
pandoc                    1.19.2.1             ha5e8f32_1
pandocfilters             1.4.2            py27hed78c4e_1
partd                     0.3.8            py27h7560dbf_0
pathlib2                  2.3.0            py27he09da1e_0
pexpect                   4.2.1            py27hc4e4961_0
pickleshare               0.7.4            py27h37e3d41_0
pip                       9.0.1                    py27_1
prompt_toolkit            1.0.15           py27h4a7b9c2_0
psutil                    5.2.2            py27h59435ec_0
ptyprocess                0.5.2            py27h70f6364_0
pycosat                   0.6.2                    py27_0
pycparser                 2.17                     py27_0
pygments                  2.2.0            py27h1a556bb_0
pyopenssl                 17.0.0                   py27_0
pyparsing                 2.1.4                    py27_0
pyqt                      5.6.0                    py27_2
pysam                     0.10.0               haccff36_3    ipyrad
python                    2.7.13                        0
python-dateutil           2.6.1            py27hd56c96b_1
pytz                      2017.2           py27hb891d23_1
pyyaml                    3.12             py27ha7932d0_1
pyzmq                     16.0.2           py27he61c07e_2
qt                        5.6.2                         2
qtconsole                 4.3.1            py27hdc90b4f_0
readline                  6.2                           2
requests                  2.14.2                   py27_0
ruamel_yaml               0.11.14                  py27_1
scandir                   1.5              py27h77d1c80_1
scipy                     0.19.1           py27hf01dd8f_3
setuptools                36.5.0           py27h2a45cec_0
simplegeneric             0.8.1            py27h6db5e31_0
singledispatch            3.4.0.3          py27he22c18d_0
sip                       4.18.1           py27h6300f65_2
six                       1.10.0                   py27_0
snowballstemmer           1.2.1            py27h68ac032_0
sortedcontainers          1.5.7            py27h322dbbf_0
sphinx                    1.6.3            py27h11269f0_0
sphinxcontrib             1.0              py27hd2ed746_1
sphinxcontrib-websupport  1.0.1            py27h857890b_1
sqlite                    3.13.0                        0
ssl_match_hostname        3.5.0.1          py27h8780752_2
tblib                     1.3.2            py27ha684fc4_0
terminado                 0.6              py27he40bf16_0
testpath                  0.3.1            py27h72d81a5_0
tk                        8.5.18                        0
toolz                     0.8.2            py27h27228c4_0
tornado                   4.5.2            py27h29aec9e_0
traitlets                 4.3.2            py27hcf08151_0
typing                    3.6.2            py27h646fea0_0
wcwidth                   0.1.7            py27h817c265_0
webencodings              0.5.1            py27h19a9f58_1
wheel                     0.29.0                   py27_0
widgetsnbextension        3.0.2            py27h56f70de_1
xopen                     0.1.1            py27h7afb20c_0    ipyrad
yaml                      0.1.6                         0
zeromq                    4.2.2                h131e0f7_1
zict                      0.1.3            py27h5fff8b1_0
zlib                      1.2.8                         3

Dustin A. Wood
Geneticist

U.S. Geological Survey
Western Ecological Research Center
San Diego Field Station
4165 Spruance Road, Suite 200
San Diego, CA 92101
Phone: (619) 225-6432

Current Projects and Publication list <http://orcid.org/0000-0002-7668-9911>

**Comment by dawood2014** [comment]
Also, How would I go about a clean wipe and reinstall? Do you think that
would help?

I feel like I did this when I ran rm -rf miniconda2, but maybe there's
something else you can suggest? Again, really appreciate all the help.

Dustin

**Comment by isaacovercast** [comment]
Hm, well I discovered that I can reproduce this error by taking a working system and forcibly removing jupyter:

```
$ conda remove jupyter --force
$ ipyrad -h
Traceback (most recent call last):
  File "/home/isaac/miniconda2/bin/ipyrad", line 6, in <module>
    from pkg_resources import load_entry_point
  File "/home/isaac/miniconda2/lib/python2.7/site-packages/pkg_resources/__init__.py", line 3074, in <module>
    @_call_aside
  File "/home/isaac/miniconda2/lib/python2.7/site-packages/pkg_resources/__init__.py", line 3058, in _call_aside
    f(*args, **kwargs)
  File "/home/isaac/miniconda2/lib/python2.7/site-packages/pkg_resources/__init__.py", line 3087, in _initialize_master_working_set
    working_set = WorkingSet._build_master()
  File "/home/isaac/miniconda2/lib/python2.7/site-packages/pkg_resources/__init__.py", line 664, in _build_master
    ws.require(__requires__)
  File "/home/isaac/miniconda2/lib/python2.7/site-packages/pkg_resources/__init__.py", line 981, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/home/isaac/miniconda2/lib/python2.7/site-packages/pkg_resources/__init__.py", line 867, in resolve
    raise DistributionNotFound(req, requirers)
pkg_resources.DistributionNotFound: The 'jupyter' distribution was not found and is required by ipyrad
```

**Comment by isaacovercast** [comment]
Yeah, really that's the best way to reinstall `rm -rf miniconda2` and then run the miniconda installer again. When did you try that last? yesterday? Try runnining the `rm -rf miniconda2` and then doing `which ipyrad` to see if there's anything floating around. I broke my system intentionally, then did the `rm` and then reinstall miniconda and ran `conda install -c ipyrad ipyrad` and it worked. This was on linux, so i'll doublecheck it works on mac, but if you can try this again it'd be great. It really should fix it....

**Comment by dawood2014** [comment]
After running the rm -rf minconda2 and then running the miniconda
installer, it worked!

Thanks again for all your help.

Dustin A. Wood
Geneticist

U.S. Geological Survey
Western Ecological Research Center
San Diego Field Station
4165 Spruance Road, Suite 200
San Diego, CA 92101
Phone: (619) 225-6432

Current Projects and Publication list <http://orcid.org/0000-0002-7668-9911>
